include:
  - path: ../../../../ecommerce_data/compose.yaml
services:
  app_postgres:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-postgres:v1.1.2
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      CONNECTION_URI: $APP_POSTGRES_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "6478"
        protocol: tcp
    depends_on:
      - postgres